language: cpp
arch: amd64
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker pull aitwatchman/ratpac:latest
  - docker run -itd --name build aitwatchman/ratpac
  - docker exec -u root build git clone https://github.com/OGgroup/FitterResponseMap.git /repo
script:
  - docker exec -u root build /wmutils/local/bin/cmake -H/repo -B/build
  - docker exec -u root build /wmutils/local/bin/cmake --build /build
  - docker exec -u root build /wmutils/local/bin/cmake --build /build --target install
