sudo: required
language: cpp

services:
  - docker

before_install:
  - docker pull aitwatchman/ratpac:latest
  - docker run -itd --name build aitwatchman/ratpac
  - docker exec build git clone https://github.com/OGgroup/FitterResponseMap.git /repo
script:
  - docker exec build cmake -H/repo -B/build
  - docker exec build cmake --build build
  - docker exec build cmake --build --target install
